spring.application.name=payee-service

server.port=8083


# ========================================
# PostgreSQL
# ========================================

spring.datasource.url=jdbc:postgresql://localhost:5432/payee_db
spring.datasource.username=postgres
spring.datasource.password=root


# ========================================
# JPA
# ========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ========================================
# Keycloak
# ========================================

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/bulk-disbursement


# ========================================
# Logging
# ========================================

logging.level.com.digipay.payee=DEBUG
logging.level.org.springframework.security=INFO


spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cache.type=redis
spring.cache.redis.time-to-live=10m
spring.cache.redis.cache-null-values=false

# ===============================
# Actuator / Prometheus
# ===============================

management.endpoints.web.exposure.include=health,info,prometheus

management.endpoint.health.show-details=always

management.prometheus.metrics.export.enabled=true
management.prometheus.metrics.export.step=10s