spring.application.name=api-gateway

server.port=8081


# ==============================
# Auth Service
# ==============================

spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**

# ==============================
# Payee Service
# ==============================

spring.cloud.gateway.server.webmvc.routes[1].id=payee-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/payees/**

# ==============================
# Scheme Service
# ==============================

spring.cloud.gateway.server.webmvc.routes[2].id=scheme-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/schemes/**


# ==============================
# Disbursement Service
# ==============================

spring.cloud.gateway.server.webmvc.routes[3].id=disbursement-service
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/disbursements/**

# ==============================
# Keycloak JWT Validation
# ==============================

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/bulk-disbursement

# ==============================
# Logging
# ==============================

logging.level.com.digipay.apigateway=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG