spring.application.name=payment-service

server.port=8087


# ==========================================
# PostgreSQL
# ==========================================

spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# Kafka
# ==========================================

spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.admin.auto-create=true
# ==========================================
# Kafka Consumer
# ==========================================

spring.kafka.consumer.group-id=payment-service

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.consumer.properties.spring.json.value.default.type=com.digipay.payment.dto.DisbursementCreatedEvent

spring.kafka.consumer.properties.spring.json.use.type.headers=false
# ==========================================
# Kafka Producer
# ==========================================

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# Kafka logging
logging.level.org.apache.kafka=ERROR
logging.level.org.springframework.kafka=ERROR

# ==========================================
# Actuator
# ==========================================

management.endpoints.web.exposure.include=health,info

# Bulk processing
payment.batch-size=500
payment.thread-pool-size=4

