spring.application.name=scheme-service
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/scheme_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Validation / errors
server.error.include-message=always

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/bulk-disbursement
