spring.application.name=disbursement-service

server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/disbursement_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/bulk-disbursement

logging.level.com.digipay.disbursement=DEBUG
logging.level.org.springframework.security=INFO

# Kafka
# ==========================================

spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.admin.auto-create=true
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# ==========================================
# Kafka Producer
# ==========================================

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# ==========================================
# Actuator
# ==========================================

management.endpoints.web.exposure.include=health,info

# Kafka logging
logging.level.org.apache.kafka=ERROR
logging.level.org.springframework.kafka=ERROR