spring.application.name=auth-service

server.port=8082

keycloak.server-url=http://localhost:8080
keycloak.realm=bulk-disbursement

keycloak.client-id=auth-service
keycloak.client-secret=avuR4Fta9L70ualSkJF5HzTeVD3B7yU7

keycloak.default-role=DISBURSEMENT_OPERATOR

management.endpoints.web.exposure.include=health,info